from flask import request
from flask_restful import Resource
from models.user import User
from models.db import db

#Class and def
class Users(Resource):
    def get(self):
        users=User.find_all() #get all the information from the user table
        return [u.json() for u in users],200# return the user as json
    def post(self):
        data=request.get_json()#return thre requested data as json
        user=User(**data)#like the spreed operator since we will increase the number of elments
        user.create()#create the user instance in the database
        return user.json(),201
class UserDetails(Resource):
    def get(self,id):
        pass
    def put(self,id):
        data=request.get_json()#pull the data as json
        user=User.find_by_id(id)#find the uuid becuase its auto-generated by the python 
        for k in data.keys():
            user[k]=data[k]
        db.session.commit()
        return user.json(),200
    def delete(self,id):
        id=User.find_by_id(id)
        if not user:
            return {'message':"no such user with this id."},404
        session.delete(user)
        db.session.commit()
        return {"message":"User deleted","paylod":id}
        