"""initial migrations

Revision ID: e0d4e053dcc5
Revises: d815bc90abf8
Create Date: 2024-07-08 00:45:01.617413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0d4e053dcc5'
down_revision = 'd815bc90abf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('theatre_id',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('theatre_id',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###
